CREATE TABLE ACUMULADO ( 
	ID INTEGER PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL, 
    PRIMER_PARCIAL FLOAT NOT NULL, 
    SEGUNDO_PARCIAL FLOAT NOT NULL 
);

SELECT NOMBRE, ((PRIMER_PARCIAL + SEGUNDO_PARCIAL) / 2) AS 'PROMEDIO' FROM acumulado WHERE ((PRIMER_PARCIAL + SEGUNDO_PARCIAL) / 2) < 90; 

UPDATE acumulado SET PRIMER_PARCIAL = 90 WHERE ID = 2;

UPDATE acumulado SET PRIMER_PARCIAL = 100, SEGUNDO_PARCIAL = 100 WHERE ID <= 1; 

DELETE FROM acumulado WHERE ID = 0; 